name: Hello World

# trigger: alleen manueel
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check runner info
        run: uname -a

      - name: Say hello
        run: echo "Hello, world!"
        